config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, :list, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(valid_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: "Bookmark was successfully added."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(params[:id]), status: :see_other
  end

  private

  def valid_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(valid_params)
    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def valid_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment%>
  <%= f.association :movie %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
 <% @lists.each do |list| %>
 <li><%= link_to list.name, list_path(list.id)%></li>
 <% end %>
</ul>

<p><%= link_to "Make a new list", new_list_path %></p>

app/views/lists/new.html.erb
<h1>Make a new list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name%>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/lists/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= @list.name %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to "Delete this list", list_path(@list),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to "Create a new bookmark", new_list_bookmark_path(params[:id]) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to "Back to all lists", lists_path %></a>
      </li>
    </ul>
  </div>
<h5 class="nav-flex-right">Bookmarks</h5>
</nav>



<% @bookmarks.each do |bookmark| %>
<div class="jumbotron jumbotron-fluid" style="background-image: url(https://source.unsplash.com/random)">
  <div class="container">
    <h1 class="display-4"><%= bookmark.movie.title %></h1>
    <p class="lead"><%= bookmark.comment %></p>
    <p><%= link_to "Delete this bookmark", bookmark_path(bookmark),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %></p>
  </div>
</div>
<% end %>